vim.o.termguicolors = true
if vim.g.colors_name then vim.cmd("hi clear") end
vim.g.colors_name = "mytheme-frappe"
local h = vim.api.nvim_set_hl
h(0, "DashboardFooter", { fg = "#e5c890", italic = true })
h(0, "DashboardMruTitle", { fg = "#99d1db" })
h(0, "DashboardProjectTitle", { fg = "#99d1db" })
h(0, "DashboardFiles", { fg = "#babbf1" })
h(0, "DashboardKey", { fg = "#ef9f76" })
h(0, "DashboardDesc", { fg = "#8caaee" })
h(0, "DashboardIcon", { fg = "#f4b8e4", bold = true })
h(0, "DiffAdd", { bg = "#455052" })
h(0, "DiffChange", { bg = "#363C52" })
h(0, "DiffDelete", { bg = "#514251" })
h(0, "DiffText", { bg = "#4C5778" })
h(0, "healthError", { fg = "#e78284" })
h(0, "healthSuccess", { fg = "#81c8be" })
h(0, "healthWarning", { fg = "#e5c890" })
h(0, "GlyphPalette1", { fg = "#e78284" })
h(0, "GlyphPalette2", { fg = "#81c8be" })
h(0, "GlyphPalette3", { fg = "#e5c890" })
h(0, "GlyphPalette4", { fg = "#8caaee" })
h(0, "GlyphPalette6", { fg = "#81c8be" })
h(0, "GlyphPalette7", { fg = "#c6d0f5" })
h(0, "GlyphPalette9", { fg = "#e78284" })
h(0, "rainbow1", { fg = "#e78284" })
h(0, "rainbow2", { fg = "#ef9f76" })
h(0, "rainbow3", { fg = "#e5c890" })
h(0, "rainbow4", { fg = "#a6d189" })
h(0, "rainbow5", { fg = "#85c1dc" })
h(0, "rainbow6", { fg = "#babbf1" })
h(0, "csvCol0", { fg = "#e78284" })
h(0, "csvCol1", { fg = "#ef9f76" })
h(0, "csvCol2", { fg = "#e5c890" })
h(0, "csvCol3", { fg = "#a6d189" })
h(0, "csvCol4", { fg = "#99d1db" })
h(0, "csvCol5", { fg = "#8caaee" })
h(0, "csvCol6", { fg = "#babbf1" })
h(0, "csvCol7", { fg = "#ca9ee6" })
h(0, "csvCol8", { fg = "#f4b8e4" })
h(0, "markdownHeadingDelimiter", { fg = "#ef9f76", bold = true })
h(0, "markdownCode", { fg = "#eebebe" })
h(0, "markdownCodeBlock", { fg = "#eebebe" })
h(0, "markdownLinkText", { fg = "#8caaee", underline = true })
h(0, "markdownH1", { link = "rainbow1" })
h(0, "markdownH2", { link = "rainbow2" })
h(0, "markdownH3", { link = "rainbow3" })
h(0, "markdownH4", { link = "rainbow4" })
h(0, "markdownH5", { link = "rainbow5" })
h(0, "markdownH6", { link = "rainbow6" })
h(0, "Directory", { fg = "#8caaee" })
h(0, "EndOfBuffer", { fg = "#51576d" })
h(0, "ErrorMsg", { fg = "#e78284", bold = true, italic = true })
h(0, "VertSplit", { fg = "#51576d" })
h(0, "Folded", { fg = "#8caaee", bg = "NONE" })
h(0, "FoldColumn", { fg = "#737994" })
h(0, "SignColumn", { fg = "#51576d" })
h(0, "SignColumnSB", { fg = "#51576d", bg = "#232634" })
h(0, "Substitute", { fg = "#f4b8e4", bg = "#51576d" })
h(0, "LineNr", { fg = "#51576d" })
h(0, "CursorLineNr", { fg = "#babbf1" })
h(0, "FlashBackdrop", { fg = "#737994" })
h(0, "FlashLabel", { fg = "#a6d189", bold = true, bg = "NONE" })
h(0, "FlashMatch", { fg = "#babbf1", bg = "NONE" })
h(0, "FlashCurrent", { fg = "#ef9f76", bg = "NONE" })
h(0, "FlashPrompt", { link = "NormalFloat" })
h(0, "NonText", { fg = "#737994" })
h(0, "Normal", { fg = "#c6d0f5", bg = "NONE" })
h(0, "NormalNC", { fg = "#c6d0f5", bg = "NONE" })
h(0, "NormalSB", { fg = "#c6d0f5", bg = "#232634" })
h(0, "NormalFloat", { fg = "#c6d0f5", bg = "#292c3c" })
h(0, "FloatBorder", { fg = "#8caaee", bg = "#292c3c" })
h(0, "FloatTitle", { fg = "#a5adce", bg = "#292c3c" })
h(0, "FloatShadow", { bg = "#737994", blend = 80 })
h(0, "FloatShadowThrough", { bg = "#737994", blend = 100 })
h(0, "Pmenu", { fg = "#949cbb", bg = "NONE" })
h(0, "GitSignsAdd", { fg = "#a6d189" })
h(0, "GitSignsChange", { fg = "#e5c890" })
h(0, "GitSignsDelete", { fg = "#e78284" })
h(0, "GitSignsCurrentLineBlame", { fg = "#51576d" })
h(0, "GitSignsAddPreview", { fg = "#a6d189", bg = "NONE" })
h(0, "GitSignsDeletePreview", { fg = "#e78284", bg = "NONE" })
h(0, "GitSignsAddInline", { fg = "#303446", bold = true, bg = "#a6d189" })
h(0, "GitSignsDeleteInline", { fg = "#303446", bold = true, bg = "#e78284" })
h(0, "GitSignsChangeInline", { fg = "#303446", bold = true, bg = "#8caaee" })
h(0, "GitSignsDeleteVirtLn", { fg = "#e78284", bg = "NONE" })
h(0, "ComplHintMore", { link = "Question" })
h(0, "Question", { fg = "#8caaee" })
h(0, "QuickFixLine", { bold = true, bg = "#474D61" })
h(0, "Search", { fg = "#c6d0f5", bg = "#506373" })
h(0, "IncSearch", { fg = "#292c3c", bg = "#8FC1CC" })
h(0, "CurSearch", { fg = "#292c3c", bg = "#e78284" })
h(0, "SpecialKey", { link = "NonText" })
h(0, "SpellBad", { undercurl = true, sp = "#e78284" })
h(0, "SpellCap", { undercurl = true, sp = "#e5c890" })
h(0, "SpellLocal", { undercurl = true, sp = "#8caaee" })
h(0, "SpellRare", { undercurl = true, sp = "#a6d189" })
h(0, "StatusLine", { fg = "#c6d0f5", bg = "NONE" })
h(0, "StatusLineNC", { fg = "#51576d", bg = "NONE" })
h(0, "TabLine", { fg = "#737994", bg = "#232634" })
h(0, "TabLineFill", { bg = "NONE" })
h(0, "TabLineSel", { link = "Normal" })
h(0, "TermCursor", { fg = "#303446", bg = "#f2d5cf" })
h(0, "@keyword.function", { fg = "#ca9ee6" })
h(0, "@keyword.operator", { fg = "#ca9ee6" })
h(0, "@keyword.import", { link = "Include" })
h(0, "@keyword.repeat", { link = "Repeat" })
h(0, "@keyword.return", { fg = "#ca9ee6" })
h(0, "@keyword.debug", { link = "Exception" })
h(0, "@keyword.exception", { link = "Exception" })
h(0, "@keyword.conditional", { link = "Conditional" })
h(0, "BlinkCmpKindText", { fg = "#a6d189" })
h(0, "BlinkCmpKindMethod", { fg = "#8caaee" })
h(0, "BlinkCmpKindFunction", { fg = "#8caaee" })
h(0, "BlinkCmpKindConstructor", { fg = "#8caaee" })
h(0, "BlinkCmpKindField", { fg = "#a6d189" })
h(0, "BlinkCmpKindVariable", { fg = "#eebebe" })
h(0, "BlinkCmpKindClass", { fg = "#e5c890" })
h(0, "BlinkCmpKindInterface", { fg = "#e5c890" })
h(0, "BlinkCmpKindModule", { fg = "#8caaee" })
h(0, "BlinkCmpKindProperty", { fg = "#8caaee" })
h(0, "BlinkCmpKindUnit", { fg = "#a6d189" })
h(0, "BlinkCmpKindValue", { fg = "#ef9f76" })
h(0, "BlinkCmpKindEnum", { fg = "#e5c890" })
h(0, "BlinkCmpKindKeyword", { fg = "#ca9ee6" })
h(0, "BlinkCmpKindSnippet", { fg = "#eebebe" })
h(0, "BlinkCmpKindColor", { fg = "#e78284" })
h(0, "BlinkCmpKindFile", { fg = "#8caaee" })
h(0, "BlinkCmpKindReference", { fg = "#e78284" })
h(0, "BlinkCmpKindFolder", { fg = "#8caaee" })
h(0, "BlinkCmpKindEnumMember", { fg = "#81c8be" })
h(0, "BlinkCmpKindConstant", { fg = "#ef9f76" })
h(0, "BlinkCmpKindStruct", { fg = "#8caaee" })
h(0, "BlinkCmpKindEvent", { fg = "#8caaee" })
h(0, "BlinkCmpKindOperator", { fg = "#99d1db" })
h(0, "BlinkCmpKindTypeParameter", { fg = "#ea999c" })
h(0, "BlinkCmpKindCopilot", { fg = "#81c8be" })
h(0, "BlinkCmpMenuBorder", { fg = "#8caaee", bg = "NONE" })
h(0, "BlinkCmpDocBorder", { link = "FloatBorder" })
h(0, "LspReferenceText", { bg = "#51576d" })
h(0, "LspReferenceRead", { bg = "#51576d" })
h(0, "LspReferenceWrite", { bg = "#51576d" })
h(0, "DiagnosticVirtualTextError", { fg = "#e78284", italic = true, bg = "NONE" })
h(0, "DiagnosticVirtualTextWarn", { fg = "#e5c890", italic = true, bg = "NONE" })
h(0, "DiagnosticVirtualTextInfo", { fg = "#99d1db", italic = true, bg = "NONE" })
h(0, "DiagnosticVirtualTextHint", { fg = "#81c8be", italic = true, bg = "NONE" })
h(0, "DiagnosticVirtualTextOk", { fg = "#a6d189", italic = true, bg = "NONE" })
h(0, "DiagnosticError", { fg = "#e78284", italic = true, bg = "NONE" })
h(0, "DiagnosticWarn", { fg = "#e5c890", italic = true, bg = "NONE" })
h(0, "DropBarMenuHoverEntry", { link = "Visual" })
h(0, "DropBarMenuHoverIcon", { reverse = true })
h(0, "DropBarMenuHoverSymbol", { bold = true })
h(0, "DropBarIconUISeparator", { fg = "#838ba7" })
h(0, "DropBarKindArray", { fg = "#c6d0f5" })
h(0, "DiagnosticUnderlineInfo", { underline = true, sp = "#99d1db" })
h(0, "DropBarKindBoolean", { fg = "#c6d0f5" })
h(0, "DiagnosticUnderlineOk", { underline = true, sp = "#a6d189" })
h(0, "DropBarKindBreakStatement", { fg = "#c6d0f5" })
h(0, "DiagnosticFloatingWarn", { fg = "#e5c890" })
h(0, "DropBarKindCall", { fg = "#c6d0f5" })
h(0, "DiagnosticFloatingHint", { fg = "#81c8be" })
h(0, "DropBarKindCaseStatement", { fg = "#c6d0f5" })
h(0, "DiagnosticSignError", { fg = "#e78284" })
h(0, "DropBarKindClass", { fg = "#c6d0f5" })
h(0, "DiagnosticSignInfo", { fg = "#99d1db" })
h(0, "DropBarKindConstant", { fg = "#c6d0f5" })
h(0, "DiagnosticSignOk", { fg = "#a6d189" })
h(0, "DropBarKindConstructor", { fg = "#c6d0f5" })
h(0, "LspDiagnosticsDefaultWarning", { fg = "#e5c890" })
h(0, "DropBarKindContinueStatement", { fg = "#c6d0f5" })
h(0, "LspDiagnosticsDefaultHint", { fg = "#81c8be" })
h(0, "DropBarKindDeclaration", { fg = "#c6d0f5" })
h(0, "LspDiagnosticsError", { fg = "#e78284" })
h(0, "DropBarKindDelete", { fg = "#c6d0f5" })
h(0, "LspDiagnosticsInformation", { fg = "#99d1db" })
h(0, "DropBarKindDoStatement", { fg = "#c6d0f5" })
h(0, "DropBarKindElseStatement", { fg = "#c6d0f5" })
h(0, "DropBarKindEnum", { fg = "#c6d0f5" })
h(0, "DropBarKindEnumMember", { fg = "#c6d0f5" })
h(0, "DropBarKindEvent", { fg = "#c6d0f5" })
h(0, "DropBarKindField", { fg = "#c6d0f5" })
h(0, "DropBarKindFile", { fg = "#c6d0f5" })
h(0, "DropBarKindFolder", { fg = "#c6d0f5" })
h(0, "DropBarKindForStatement", { fg = "#c6d0f5" })
h(0, "DropBarKindFunction", { fg = "#c6d0f5" })
h(0, "DropBarKindIdentifier", { fg = "#c6d0f5" })
h(0, "DropBarKindIfStatement", { fg = "#c6d0f5" })
h(0, "DropBarKindInterface", { fg = "#c6d0f5" })
h(0, "DropBarKindKeyword", { fg = "#c6d0f5" })
h(0, "DropBarKindList", { fg = "#c6d0f5" })
h(0, "DropBarKindMacro", { fg = "#c6d0f5" })
h(0, "DropBarKindMarkdownH1", { fg = "#c6d0f5" })
h(0, "DropBarKindMarkdownH2", { fg = "#c6d0f5" })
h(0, "DropBarKindMarkdownH3", { fg = "#c6d0f5" })
h(0, "DropBarKindMarkdownH5", { fg = "#c6d0f5" })
h(0, "DropBarKindMarkdownH4", { fg = "#c6d0f5" })
h(0, "DropBarKindMarkdownH6", { fg = "#c6d0f5" })
h(0, "@variable.member", { fg = "#babbf1" })
h(0, "DropBarKindMethod", { fg = "#c6d0f5" })
h(0, "@constant.builtin", { fg = "#ef9f76" })
h(0, "DropBarKindModule", { fg = "#c6d0f5" })
h(0, "@module", { fg = "#e5c890", italic = true })
h(0, "DropBarKindNamespace", { fg = "#c6d0f5" })
h(0, "@label", { link = "Label" })
h(0, "DropBarKindNull", { fg = "#c6d0f5" })
h(0, "@string.documentation", { fg = "#81c8be" })
h(0, "DropBarKindNumber", { fg = "#c6d0f5" })
h(0, "@string.escape", { fg = "#f4b8e4" })
h(0, "DropBarKindObject", { fg = "#c6d0f5" })
h(0, "@string.special.path", { link = "Special" })
h(0, "DropBarKindOperator", { fg = "#c6d0f5" })
h(0, "@string.special.url", { fg = "#8caaee", italic = true, underline = true })
h(0, "DropBarKindPackage", { fg = "#c6d0f5" })
h(0, "@character", { link = "Character" })
h(0, "DropBarKindProperty", { fg = "#c6d0f5" })
h(0, "@boolean", { link = "Boolean" })
h(0, "DropBarKindReference", { fg = "#c6d0f5" })
h(0, "@number.float", { link = "Float" })
h(0, "DropBarKindRepeat", { fg = "#c6d0f5" })
h(0, "@type.builtin", { fg = "#ca9ee6" })
h(0, "DropBarKindScope", { fg = "#c6d0f5" })
h(0, "@attribute", { link = "Constant" })
h(0, "DropBarKindSpecifier", { fg = "#c6d0f5" })
h(0, "@function", { link = "Function" })
h(0, "DropBarKindStatement", { fg = "#c6d0f5" })
h(0, "@function.macro", { fg = "#f4b8e4" })
h(0, "DropBarKindString", { fg = "#c6d0f5" })
h(0, "@function.method.call", { link = "Function" })
h(0, "DropBarKindStruct", { fg = "#c6d0f5" })
h(0, "@operator", { link = "Operator" })
h(0, "DropBarKindSwitchStatement", { fg = "#c6d0f5" })
h(0, "@keyword.modifier", { link = "Keyword" })
h(0, "DropBarKindType", { fg = "#c6d0f5" })
h(0, "@keyword.coroutine", { link = "Keyword" })
h(0, "DropBarKindTypeParameter", { fg = "#c6d0f5" })
h(0, "DropBarKindUnit", { fg = "#c6d0f5" })
h(0, "DropBarKindValue", { fg = "#c6d0f5" })
h(0, "DropBarKindVariable", { fg = "#c6d0f5" })
h(0, "DropBarKindWhileStatement", { fg = "#c6d0f5" })
h(0, "IblIndent", { fg = "#414559" })
h(0, "IblScope", { fg = "#c6d0f5" })
h(0, "BlinkIndent", { fg = "#414559" })
h(0, "BlinkIndentScope", { fg = "#949cbb" })
h(0, "BlinkIndentRed", { fg = "#e78284" })
h(0, "BlinkIndentOrange", { fg = "#ef9f76" })
h(0, "BlinkIndentYellow", { fg = "#e5c890" })
h(0, "BlinkIndentGreen", { fg = "#a6d189" })
h(0, "BlinkIndentCyan", { fg = "#99d1db" })
h(0, "BlinkIndentBlue", { fg = "#8caaee" })
h(0, "BlinkIndentViolet", { fg = "#ca9ee6" })
h(0, "BlinkIndentRedUnderline", { underline = true, sp = "#e78284" })
h(0, "BlinkIndentOrangeUnderline", { underline = true, sp = "#ef9f76" })
h(0, "BlinkIndentYellowUnderline", { underline = true, sp = "#e5c890" })
h(0, "BlinkIndentGreenUnderline", { underline = true, sp = "#a6d189" })
h(0, "BlinkIndentCyanUnderline", { underline = true, sp = "#99d1db" })
h(0, "BlinkIndentBlueUnderline", { underline = true, sp = "#8caaee" })
h(0, "BlinkIndentVioletUnderline", { underline = true, sp = "#ca9ee6" })
h(0, "FzfLuaNormal", { link = "NormalFloat" })
h(0, "FzfLuaBorder", { link = "FloatBorder" })
h(0, "FzfLuaTitle", { link = "FloatTitle" })
h(0, "FzfLuaHeaderBind", { fg = "#e5c890" })
h(0, "FzfLuaHeaderText", { fg = "#ef9f76" })
h(0, "FzfLuaDirPart", { link = "NonText" })
h(0, "FzfLuaFzfMatch", { fg = "#8caaee" })
h(0, "FzfLuaFzfPrompt", { fg = "#8caaee" })
h(0, "FzfLuaPathColNr", { fg = "#8caaee" })
h(0, "FzfLuaPathLineNr", { fg = "#a6d189" })
h(0, "FzfLuaBufName", { fg = "#ca9ee6" })
h(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
h(0, "FzfLuaBufFlagCur", { fg = "#ef9f76" })
h(0, "FzfLuaBufFlagAlt", { fg = "#8caaee" })
h(0, "FzfLuaTabTitle", { fg = "#99d1db" })
h(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
h(0, "MiniClueDescSingle", { link = "NormalFloat" })
h(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
h(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
h(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
h(0, "MiniClueTitle", { link = "FloatTitle" })
h(0, "RenderMarkdownH1", { fg = "#e78284" })
h(0, "MiniCursorword", { underline = true })
h(0, "MiniCursorwordCurrent", { underline = true })
h(0, "MiniDepsChangeAdded", { link = "diffAdded" })
h(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
h(0, "MiniDepsHint", { link = "DiagnosticHint" })
h(0, "CmpItemAbbr", { fg = "#949cbb" })
h(0, "CmpItemAbbrDeprecated", { fg = "#737994", strikethrough = true })
h(0, "CmpItemKind", { fg = "#8caaee" })
h(0, "MiniDepsTitle", { link = "Title" })
h(0, "MiniDepsTitleError", { fg = "#303446", bg = "#e78284" })
h(0, "MiniDepsTitleSame", { link = "DiffText" })
h(0, "MiniDepsTitleUpdate", { fg = "#303446", bg = "#a6d189" })
h(0, "MiniDiffSignAdd", { fg = "#a6d189" })
h(0, "MiniDiffSignChange", { fg = "#e5c890" })
h(0, "CmpItemKindMethod", { fg = "#8caaee" })
h(0, "MiniDiffOverAdd", { link = "DiffAdd" })
h(0, "CmpItemKindFunction", { fg = "#8caaee" })
h(0, "MiniDiffOverContext", { link = "DiffChange" })
h(0, "MiniDiffOverDelete", { link = "DiffDelete" })
h(0, "MiniFilesBorder", { link = "FloatBorder" })
h(0, "CmpItemKindField", { fg = "#a6d189" })
h(0, "MiniFilesCursorLine", { link = "CursorLine" })
h(0, "CmpItemKindEnum", { fg = "#a6d189" })
h(0, "CmpItemKindUnit", { fg = "#a6d189" })
h(0, "CmpItemKindClass", { fg = "#e5c890" })
h(0, "CmpItemKindVariable", { fg = "#eebebe" })
h(0, "MiniFilesTitleFocused", { fg = "#a5adce", bold = true, bg = "#292c3c" })
h(0, "MiniHipatternsFixme", { fg = "#303446", bold = true, bg = "#e78284" })
h(0, "MiniHipatternsHack", { fg = "#303446", bold = true, bg = "#e5c890" })
h(0, "MiniHipatternsNote", { fg = "#303446", bold = true, bg = "#99d1db" })
h(0, "MiniHipatternsTodo", { fg = "#303446", bold = true, bg = "#81c8be" })
h(0, "MiniIconsAzure", { fg = "#85c1dc" })
h(0, "MiniIconsBlue", { fg = "#8caaee" })
h(0, "MiniIconsCyan", { fg = "#81c8be" })
h(0, "MiniIconsGreen", { fg = "#a6d189" })
h(0, "MiniIconsGrey", { fg = "#c6d0f5" })
h(0, "MiniIconsOrange", { fg = "#ef9f76" })
h(0, "MiniIconsPurple", { fg = "#ca9ee6" })
h(0, "MiniIconsRed", { fg = "#e78284" })
h(0, "MiniIconsYellow", { fg = "#e5c890" })
h(0, "MiniIndentscopeSymbol", { fg = "#949cbb" })
h(0, "MiniJump", { fg = "#949cbb", bg = "#f4b8e4" })
h(0, "MiniJump2dDim", { fg = "#737994" })
h(0, "MiniJump2dSpot", { bg = "#303446", fg = "#ef9f76", bold = true, underline = true })
h(0, "MiniJump2dSpotAhead", { fg = "#81c8be", bg = "#2A2D3E" })
h(0, "MiniJump2dSpotUnique", { fg = "#99d1db", bold = true, bg = "#303446" })
h(0, "MiniMapNormal", { link = "NormalFloat" })
h(0, "MiniMapSymbolCount", { link = "Special" })
h(0, "MiniMapSymbolLine", { link = "Title" })
h(0, "MiniMapSymbolView", { link = "Delimiter" })
h(0, "MiniNotifyBorder", { link = "FloatBorder" })
h(0, "MiniNotifyNormal", { link = "NormalFloat" })
h(0, "MiniNotifyTitle", { link = "FloatTitle" })
h(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
h(0, "MiniPickBorder", { link = "FloatBorder" })
h(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
h(0, "MiniPickBorderText", { fg = "#ca9ee6", bg = "#292c3c" })
h(0, "MiniPickIconDirectory", { link = "Directory" })
h(0, "MiniPickIconFile", { link = "MiniPickNormal" })
h(0, "MiniPickNormal", { link = "NormalFloat" })
h(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
h(0, "MiniPickMatchCurrent", { fg = "#eebebe", bold = true, bg = "#414559" })
h(0, "MiniPickMatchMarked", { link = "Visual" })
h(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
h(0, "MiniPickPreviewLine", { link = "CursorLine" })
h(0, "MiniPickPreviewRegion", { link = "IncSearch" })
h(0, "MiniPickPrompt", { fg = "#c6d0f5", bg = "#292c3c" })
h(0, "MiniPickPromptCaret", { fg = "#eebebe", bg = "#292c3c" })
h(0, "MiniPickPromptPrefix", { fg = "#eebebe", bg = "#292c3c" })
h(0, "MiniStarterCurrent", {  })
h(0, "MiniStarterFooter", { fg = "#e5c890", italic = true })
h(0, "MiniStarterHeader", { fg = "#8caaee" })
h(0, "MiniStarterInactive", { fg = "#626880", italic = true })
h(0, "MiniStarterItem", { fg = "#c6d0f5" })
h(0, "MiniStarterItemBullet", { fg = "#8caaee" })
h(0, "MiniStarterItemPrefix", { fg = "#f4b8e4" })
h(0, "MiniStarterSection", { fg = "#eebebe" })
h(0, "MiniStarterQuery", { fg = "#a6d189" })
h(0, "MiniStatuslineDevinfo", { fg = "#b5bfe2", bg = "#51576d" })
h(0, "MiniStatuslineFileinfo", { fg = "#b5bfe2", bg = "#51576d" })
h(0, "MiniStatuslineFilename", { fg = "#c6d0f5", bg = "#292c3c" })
h(0, "MiniStatuslineInactive", { fg = "#8caaee", bg = "#292c3c" })
h(0, "MiniStatuslineModeCommand", { fg = "#303446", bold = true, bg = "#ef9f76" })
h(0, "MiniStatuslineModeInsert", { fg = "#303446", bold = true, bg = "#a6d189" })
h(0, "MiniStatuslineModeNormal", { fg = "#292c3c", bold = true, bg = "#8caaee" })
h(0, "MiniStatuslineModeOther", { fg = "#303446", bold = true, bg = "#81c8be" })
h(0, "MiniStatuslineModeReplace", { fg = "#303446", bold = true, bg = "#e78284" })
h(0, "MiniStatuslineModeVisual", { fg = "#303446", bold = true, bg = "#ca9ee6" })
h(0, "MiniSurround", { fg = "#51576d", bg = "#f4b8e4" })
h(0, "MiniTablineCurrent", { italic = true, sp = "#e78284", fg = "#c6d0f5", bold = true, underline = true, bg = "#303446" })
h(0, "MiniTablineFill", { bg = "NONE" })
h(0, "MiniTablineHidden", { fg = "#c6d0f5", bg = "NONE" })
h(0, "MiniTablineModifiedCurrent", { italic = true, bg = "NONE", fg = "#e78284", bold = true })
h(0, "MiniTablineModifiedHidden", { fg = "#e78284", bg = "NONE" })
h(0, "MiniTablineModifiedVisible", { fg = "#e78284", bg = "NONE" })
h(0, "MiniTablineTabpagesection", { fg = "#51576d", bg = "#303446" })
h(0, "MiniTablineVisible", { bg = "NONE" })
h(0, "MiniTestEmphasis", { bold = true })
h(0, "MiniTestFail", { fg = "#e78284", bold = true })
h(0, "MiniTestPass", { fg = "#a6d189", bold = true })
h(0, "MiniTrailspace", { bg = "#e78284" })
h(0, "AlphaShortcut", { fg = "#a6d189" })
h(0, "AlphaHeader", { fg = "#8caaee" })
h(0, "AlphaHeaderLabel", { fg = "#ef9f76" })
h(0, "AlphaButtons", { fg = "#babbf1" })
h(0, "AlphaFooter", { fg = "#e5c890", italic = true })
h(0, "BlinkCmpLabel", { fg = "#949cbb" })
h(0, "BlinkCmpLabelDeprecated", { fg = "#737994", strikethrough = true })
h(0, "BlinkCmpKind", { fg = "#8caaee" })
h(0, "BlinkCmpMenu", { link = "Pmenu" })
h(0, "BlinkCmpDoc", { link = "NormalFloat" })
h(0, "BlinkCmpLabelMatch", { link = "PmenuMatch" })
h(0, "BlinkCmpMenuSelection", { bold = true, bg = "#51576d" })
h(0, "BlinkCmpScrollBarGutter", { bg = "#51576d" })
h(0, "BlinkCmpScrollBarThumb", { bg = "#737994" })
h(0, "BlinkCmpLabelDescription", { link = "PmenuExtra" })
h(0, "BlinkCmpLabelDetail", { link = "PmenuExtra" })
h(0, "BlinkCmpSignatureHelpBorder", { link = "FloatBorder" })
h(0, "LspDiagnosticsUnderlineHint", { underline = true, sp = "#81c8be" })
h(0, "LspCodeLens", { fg = "#737994" })
h(0, "LspCodeLensSeparator", { link = "LspCodeLens" })
h(0, "LspInlayHint", { fg = "#737994", bg = "NONE" })
h(0, "LspInfoBorder", { link = "FloatBorder" })
h(0, "LspDiagnosticsDefaultInformation", { fg = "#99d1db" })
h(0, "LspSignatureActiveParameter", { bold = true, bg = "#414559" })
h(0, "WarningMsg", { fg = "#e5c890" })
h(0, "LspDiagnosticsWarning", { fg = "#e5c890" })
h(0, "LspDiagnosticsHint", { fg = "#81c8be" })
h(0, "CmpItemKindInterface", { fg = "#e5c890" })
h(0, "MiniDepsPlaceholder", { link = "Comment" })
h(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
h(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
h(0, "RenderMarkdownH2Bg", { bg = "#655253" })
h(0, "WinBarNC", { link = "WinBar" })
h(0, "WinBar", { fg = "#f2d5cf" })
h(0, "WildMenu", { bg = "#737994" })
h(0, "Whitespace", { fg = "#51576d" })
h(0, "VisualNOS", { bold = true, bg = "#51576d" })
h(0, "Visual", { bold = true, bg = "#51576d" })
h(0, "Title", { fg = "#8caaee", bold = true })
h(0, "TermCursorNC", { fg = "#303446", bg = "#949cbb" })
h(0, "RenderMarkdownH2", { fg = "#ef9f76" })
h(0, "LspDiagnosticsUnderlineInformation", { underline = true, sp = "#99d1db" })
h(0, "ComplHint", { fg = "#a5adce" })
h(0, "PreInsert", { fg = "#949cbb" })
h(0, "ComplMatchIns", { link = "PreInsert" })
h(0, "PmenuExtraSel", { fg = "#737994", bold = true, bg = "#414559" })
h(0, "PmenuExtra", { fg = "#737994" })
h(0, "PmenuThumb", { bg = "#737994" })
h(0, "PmenuSbar", { bg = "#414559" })
h(0, "PmenuMatchSel", { bold = true })
h(0, "PmenuMatch", { fg = "#c6d0f5", bold = true })
h(0, "PmenuSel", { bold = true, bg = "#414559" })
h(0, "NeogitBranch", { fg = "#ef9f76", bold = true })
h(0, "NeogitRemote", { fg = "#a6d189", bold = true })
h(0, "NeogitUnmergedInto", { link = "Function" })
h(0, "NeogitUnpulledFrom", { link = "Function" })
h(0, "NeogitObjectId", { link = "Comment" })
h(0, "NeogitStash", { link = "Comment" })
h(0, "NeogitRebaseDone", { link = "Comment" })
h(0, "NeogitHunkHeader", { fg = "#5E6F9A", bg = "#393F56" })
h(0, "NeogitHunkHeaderHighlight", { fg = "#8caaee", bg = "#444D6A" })
h(0, "NeogitDiffContextHighlight", { bg = "#414559" })
h(0, "NeogitDiffDeleteHighlight", { fg = "#E28E95", bg = "#6F4F5B" })
h(0, "NeogitDiffAddHighlight", { fg = "#ABD199", bg = "#596A5D" })
h(0, "NeogitDiffDelete", { fg = "#C27278", bg = "#413B4C" })
h(0, "NeogitDiffDeleteInline", { bold = true, bg = "#8C5B65" })
h(0, "NeogitDiffAdd", { fg = "#8EB27C", bg = "#3B434C" })
h(0, "NeogitDiffAddInline", { bold = true, bg = "#6B8368" })
h(0, "NeogitCommitViewHeader", { fg = "#98B2EF", bg = "#4C5778" })
h(0, "NeogitChangeModified", { fg = "#8caaee", bold = true })
h(0, "NeogitChangeDeleted", { fg = "#e78284", bold = true })
h(0, "NeogitChangeAdded", { fg = "#a6d189", bold = true })
h(0, "NeogitChangeRenamed", { fg = "#ca9ee6", bold = true })
h(0, "NeogitChangeUpdated", { fg = "#ef9f76", bold = true })
h(0, "NeogitChangeCopied", { fg = "#f4b8e4", bold = true })
h(0, "NeogitChangeBothModified", { fg = "#e5c890", bold = true })
h(0, "NeogitChangeNewFile", { fg = "#a6d189", bold = true })
h(0, "NeogitUntrackedfiles", { fg = "#ca9ee6", bold = true })
h(0, "NeogitUnstagedchanges", { fg = "#ca9ee6", bold = true })
h(0, "NeogitUnmergedchanges", { fg = "#ca9ee6", bold = true })
h(0, "NeogitUnpulledchanges", { fg = "#ca9ee6", bold = true })
h(0, "NeogitRecentcommits", { fg = "#ca9ee6", bold = true })
h(0, "NeogitStagedchanges", { fg = "#ca9ee6", bold = true })
h(0, "NeogitStashes", { fg = "#ca9ee6", bold = true })
h(0, "NeogitRebasing", { fg = "#ca9ee6", bold = true })
h(0, "NeogitNotificationInfo", { fg = "#8caaee" })
h(0, "NeogitNotificationWarning", { fg = "#e5c890" })
h(0, "NeogitNotificationError", { fg = "#e78284" })
h(0, "NeogitGraphRed", { fg = "#e78284" })
h(0, "NeogitGraphWhite", { fg = "#303446" })
h(0, "NeogitGraphYellow", { fg = "#e5c890" })
h(0, "NeogitGraphGreen", { fg = "#a6d189" })
h(0, "NeogitGraphCyan", { fg = "#8caaee" })
h(0, "NeogitGraphBlue", { fg = "#8caaee" })
h(0, "NeogitGraphPurple", { fg = "#babbf1" })
h(0, "NeogitGraphGray", { fg = "#b5bfe2" })
h(0, "NeogitGraphOrange", { fg = "#ef9f76" })
h(0, "NeogitGraphBoldRed", { fg = "#e78284", bold = true })
h(0, "NeogitGraphBoldWhite", { bold = true })
h(0, "@markup.link.label", { fg = "#babbf1" })
h(0, "NeogitGraphBoldYellow", { fg = "#e5c890", bold = true })
h(0, "NeogitGraphBoldGreen", { fg = "#a6d189", bold = true })
h(0, "NeogitGraphBoldCyan", { fg = "#8caaee", bold = true })
h(0, "NeogitGraphBoldBlue", { fg = "#8caaee", bold = true })
h(0, "NeogitGraphBoldPurple", { fg = "#babbf1", bold = true })
h(0, "NeogitGraphBoldGray", { fg = "#b5bfe2", bold = true })
h(0, "NeogitDiffContext", { bg = "#303446" })
h(0, "NeogitPopupBold", { bold = true })
h(0, "NeogitPopupSwitchKey", { fg = "#babbf1" })
h(0, "NeogitPopupOptionKey", { fg = "#babbf1" })
h(0, "NeogitPopupConfigKey", { fg = "#babbf1" })
h(0, "NeogitPopupActionKey", { fg = "#babbf1" })
h(0, "NeogitFilePath", { fg = "#8caaee", italic = true })
h(0, "NeogitDiffHeader", { fg = "#8caaee", bold = true, bg = "#303446" })
h(0, "NeogitDiffHeaderHighlight", { fg = "#ef9f76", bold = true, bg = "#303446" })
h(0, "NeogitUnpushedTo", { fg = "#babbf1", bold = true })
h(0, "NeogitFold", { fg = "NONE", bg = "NONE" })
h(0, "NeogitSectionHeader", { fg = "#ca9ee6", bold = true })
h(0, "NeogitTagName", { fg = "#e5c890" })
h(0, "NeogitTagDistance", { fg = "#8caaee" })
h(0, "NeogitWinSeparator", { link = "WinSeparator" })
h(0, "@markup.heading.html", { link = "@markup" })
h(0, "@markup.heading.1.html", { link = "@markup" })
h(0, "@markup.heading.2.html", { link = "@markup" })
h(0, "@markup.heading.3.html", { link = "@markup" })
h(0, "@markup.heading.4.html", { link = "@markup" })
h(0, "@markup.heading.5.html", { link = "@markup" })
h(0, "@markup.heading.6.html", { link = "@markup" })
h(0, "@constant.java", { fg = "#81c8be" })
h(0, "@property.css", { fg = "#8caaee" })
h(0, "@property.scss", { fg = "#8caaee" })
h(0, "@property.id.css", { fg = "#e5c890" })
h(0, "@property.class.css", { fg = "#e5c890" })
h(0, "@type.css", { fg = "#babbf1" })
h(0, "@type.tag.css", { fg = "#8caaee" })
h(0, "@string.plain.css", { fg = "#c6d0f5" })
h(0, "@number.css", { fg = "#ef9f76" })
h(0, "@keyword.directive.css", { link = "Keyword" })
h(0, "@string.special.url.html", { fg = "#a6d189" })
h(0, "@markup.link.label.html", { fg = "#c6d0f5" })
h(0, "@character.special.html", { fg = "#e78284" })
h(0, "@constructor.lua", { link = "@punctuation.bracket" })
h(0, "@constructor.python", { fg = "#99d1db" })
h(0, "@label.yaml", { fg = "#e5c890" })
h(0, "@string.special.symbol.ruby", { fg = "#eebebe" })
h(0, "@function.method.php", { link = "Function" })
h(0, "@function.method.call.php", { link = "Function" })
h(0, "@keyword.import.c", { fg = "#e5c890" })
h(0, "@keyword.import.cpp", { fg = "#e5c890" })
h(0, "@attribute.c_sharp", { fg = "#e5c890" })
h(0, "@comment.warning.gitcommit", { fg = "#e5c890" })
h(0, "@string.special.path.gitignore", { fg = "#c6d0f5" })
h(0, "gitcommitSummary", { fg = "#f2d5cf", italic = true })
h(0, "zshKSHFunction", { link = "Function" })
h(0, "@parameter", { fg = "#ea999c" })
h(0, "@field", { fg = "#babbf1" })
h(0, "@namespace", { fg = "#e5c890", italic = true })
h(0, "@float", { link = "Float" })
h(0, "@symbol", { fg = "#eebebe" })
h(0, "@string.regex", { fg = "#f4b8e4" })
h(0, "@text", { fg = "#c6d0f5" })
h(0, "@text.strong", { fg = "#e78284", bold = true })
h(0, "NeoTreeDirectoryName", { fg = "#8caaee" })
h(0, "NeoTreeDirectoryIcon", { fg = "#8caaee" })
h(0, "NeoTreeNormal", { fg = "#c6d0f5", bg = "NONE" })
h(0, "NeoTreeNormalNC", { fg = "#c6d0f5", bg = "NONE" })
h(0, "NeoTreeExpander", { fg = "#737994" })
h(0, "NeoTreeIndentMarker", { fg = "#737994" })
h(0, "NeoTreeRootName", { fg = "#8caaee", bold = true })
h(0, "NeoTreeSymbolicLinkTarget", { fg = "#f4b8e4" })
h(0, "NeoTreeModified", { fg = "#ef9f76" })
h(0, "NeoTreeGitAdded", { fg = "#a6d189" })
h(0, "NeoTreeGitConflict", { fg = "#e78284" })
h(0, "NeoTreeGitDeleted", { fg = "#e78284" })
h(0, "NeoTreeGitIgnored", { fg = "#737994" })
h(0, "NeoTreeGitModified", { fg = "#e5c890" })
h(0, "NeoTreeGitUnstaged", { fg = "#e78284" })
h(0, "NeoTreeGitUntracked", { fg = "#ca9ee6" })
h(0, "NeoTreeGitStaged", { fg = "#a6d189" })
h(0, "NeoTreeFloatBorder", { link = "FloatBorder" })
h(0, "NeoTreeFloatTitle", { link = "FloatTitle" })
h(0, "NeoTreeTitleBar", { fg = "#292c3c", bg = "#8caaee" })
h(0, "NeoTreeFileNameOpened", { fg = "#f4b8e4" })
h(0, "NeoTreeDimText", { fg = "#838ba7" })
h(0, "NeoTreeFilterTerm", { fg = "#a6d189", bold = true })
h(0, "NeoTreeTabActive", { fg = "#babbf1", bold = true, bg = "NONE" })
h(0, "NeoTreeTabInactive", { fg = "#737994", bg = "NONE" })
h(0, "NeoTreeTabSeparatorActive", { fg = "NONE", bg = "NONE" })
h(0, "NeoTreeTabSeparatorInactive", { fg = "NONE", bg = "NONE" })
h(0, "NeoTreeVertSplit", { fg = "#303446", bg = "NONE" })
h(0, "NeoTreeWinSeparator", { fg = "#51576d", bg = "NONE" })
h(0, "NeoTreeStatusLineNC", { fg = "#292c3c", bg = "#292c3c" })
h(0, "MoreMsg", { fg = "#8caaee" })
h(0, "WinSeparator", { fg = "#51576d" })
h(0, "MsgSeparator", { link = "WinSeparator" })
h(0, "ModeMsg", { fg = "#c6d0f5", bold = true })
h(0, "MatchParen", { fg = "#ef9f76", bold = true, bg = "#474D61" })
h(0, "Dimmed", { fg = "#838ba7" })
h(0, "CursorLine", { bg = "#3B3F52" })
h(0, "CursorColumn", { bg = "#292c3c" })
h(0, "CursorIM", { fg = "#303446", bg = "#f2d5cf" })
h(0, "lCursor", { fg = "#303446", bg = "#f2d5cf" })
h(0, "NvimTreeFolderName", { fg = "#8caaee" })
h(0, "NvimTreeFolderIcon", { fg = "#8caaee" })
h(0, "NvimTreeNormal", { fg = "#c6d0f5", bg = "NONE" })
h(0, "NvimTreeOpenedFolderName", { fg = "#8caaee" })
h(0, "NvimTreeEmptyFolderName", { fg = "#8caaee" })
h(0, "NvimTreeIndentMarker", { fg = "#737994" })
h(0, "NvimTreeWinSeparator", { fg = "#51576d", bg = "NONE" })
h(0, "NvimTreeRootFolder", { fg = "#babbf1", bold = true })
h(0, "NvimTreeSymlink", { fg = "#f4b8e4" })
h(0, "NvimTreeStatuslineNc", { fg = "#292c3c", bg = "#292c3c" })
h(0, "NvimTreeGitDirty", { fg = "#e5c890" })
h(0, "NvimTreeGitNew", { fg = "#8caaee" })
h(0, "NvimTreeGitDeleted", { fg = "#e78284" })
h(0, "Cursor", { fg = "#303446", bg = "#f2d5cf" })
h(0, "Conceal", { fg = "#838ba7" })
h(0, "ColorColumn", { bg = "#414559" })
h(0, "LspDiagnosticsDefaultError", { fg = "#e78284" })
h(0, "DiagnosticSignHint", { fg = "#81c8be" })
h(0, "DiagnosticSignWarn", { fg = "#e5c890" })
h(0, "DiagnosticFloatingOk", { fg = "#a6d189" })
h(0, "DiagnosticFloatingInfo", { fg = "#99d1db" })
h(0, "DiagnosticFloatingError", { fg = "#e78284" })
h(0, "DiagnosticUnderlineHint", { underline = true, sp = "#81c8be" })
h(0, "DiagnosticUnderlineWarn", { underline = true, sp = "#e5c890" })
h(0, "DiagnosticUnderlineError", { underline = true, sp = "#e78284" })
h(0, "DiagnosticOk", { fg = "#a6d189", italic = true, bg = "NONE" })
h(0, "DiagnosticHint", { fg = "#81c8be", italic = true, bg = "NONE" })
h(0, "DiagnosticInfo", { fg = "#99d1db", italic = true, bg = "NONE" })
h(0, "diffAdded", { fg = "#a6d189" })
h(0, "Changed", { fg = "#8caaee" })
h(0, "Added", { fg = "#a6d189" })
h(0, "RenderMarkdownH5Bg", { bg = "#485B70" })
h(0, "MiniFilesFile", { fg = "#c6d0f5" })
h(0, "MiniFilesNormal", { link = "NormalFloat" })
h(0, "FzfLuaBufNr", { fg = "#e5c890" })
h(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
h(0, "MiniClueBorder", { link = "FloatBorder" })
h(0, "FzfLuaTabMarker", { fg = "#e5c890" })
h(0, "FzfLuaLiveSym", { fg = "#ef9f76" })
h(0, "MiniCompletionActiveParameter", { underline = true })
h(0, "CmpItemMenu", { fg = "#c6d0f5" })
h(0, "qfLineNr", { fg = "#e5c890" })
h(0, "Todo", { fg = "#303446", bold = true, bg = "#eebebe" })
h(0, "Error", { fg = "#e78284" })
h(0, "Italic", { italic = true })
h(0, "Bold", { bold = true })
h(0, "Underlined", { underline = true })
h(0, "Debug", { link = "Special" })
h(0, "Delimiter", { fg = "#949cbb" })
h(0, "Tag", { fg = "#babbf1", bold = true })
h(0, "SpecialChar", { link = "Special" })
h(0, "Typedef", { link = "Type" })
h(0, "Type", { fg = "#e5c890" })
h(0, "Structure", { fg = "#e5c890" })
h(0, "StorageClass", { fg = "#e5c890" })
h(0, "PreCondit", { link = "PreProc" })
h(0, "NvimTreeSpecialFile", { fg = "#eebebe" })
h(0, "NvimTreeImageFile", { fg = "#c6d0f5" })
h(0, "NvimTreeOpenedFile", { fg = "#f4b8e4" })
h(0, "Macro", { fg = "#ca9ee6" })
h(0, "Define", { link = "PreProc" })
h(0, "Include", { fg = "#ca9ee6" })
h(0, "PreProc", { fg = "#f4b8e4" })
h(0, "Exception", { fg = "#ca9ee6" })
h(0, "Keyword", { fg = "#ca9ee6" })
h(0, "Operator", { fg = "#99d1db" })
h(0, "Label", { fg = "#85c1dc" })
h(0, "Repeat", { fg = "#ca9ee6" })
h(0, "Conditional", { fg = "#ca9ee6", italic = true })
h(0, "UfoFoldedFg", { fg = "#babbf1" })
h(0, "UfoFoldedEllipsis", { fg = "#232634", bg = "#8caaee" })
h(0, "Statement", { fg = "#ca9ee6" })
h(0, "Function", { fg = "#8caaee" })
h(0, "Identifier", { fg = "#eebebe" })
h(0, "Boolean", { fg = "#ef9f76" })
h(0, "Float", { link = "Number" })
h(0, "Number", { fg = "#ef9f76" })
h(0, "Character", { fg = "#81c8be" })
h(0, "String", { fg = "#a6d189" })
h(0, "Constant", { fg = "#ef9f76" })
h(0, "Special", { fg = "#f4b8e4" })
h(0, "RainbowDelimiterRed", { fg = "#e78284" })
h(0, "RainbowDelimiterYellow", { fg = "#e5c890" })
h(0, "RainbowDelimiterBlue", { fg = "#8caaee" })
h(0, "RainbowDelimiterOrange", { fg = "#ef9f76" })
h(0, "RainbowDelimiterGreen", { fg = "#a6d189" })
h(0, "RainbowDelimiterViolet", { fg = "#ca9ee6" })
h(0, "RainbowDelimiterCyan", { fg = "#81c8be" })
h(0, "MiniDiffOverChange", { link = "DiffText" })
h(0, "RenderMarkdownH4Bg", { bg = "#516059" })
h(0, "@lsp.typemod.function.builtin", { link = "@function.builtin" })
h(0, "@markup.strikethrough", { fg = "#c6d0f5", strikethrough = true })
h(0, "@markup.italic", { fg = "#e78284", italic = true })
h(0, "@markup.strong", { fg = "#e78284", bold = true })
h(0, "@markup", { fg = "#c6d0f5" })
h(0, "@comment.note", { fg = "#303446", bg = "#8caaee" })
h(0, "@comment.todo", { fg = "#303446", bg = "#eebebe" })
h(0, "@comment.hint", { fg = "#303446", bg = "#8caaee" })
h(0, "@comment.warning", { fg = "#303446", bg = "#e5c890" })
h(0, "RenderMarkdownCode", { bg = "#292c3c" })
h(0, "RenderMarkdownCodeInline", { bg = "#414559" })
h(0, "RenderMarkdownBullet", { fg = "#99d1db" })
h(0, "RenderMarkdownTableHead", { fg = "#8caaee" })
h(0, "RenderMarkdownTableRow", { fg = "#babbf1" })
h(0, "RenderMarkdownSuccess", { fg = "#a6d189" })
h(0, "RenderMarkdownInfo", { fg = "#99d1db" })
h(0, "RenderMarkdownHint", { fg = "#81c8be" })
h(0, "RenderMarkdownWarn", { fg = "#e5c890" })
h(0, "RenderMarkdownError", { fg = "#e78284" })
h(0, "@comment.error", { fg = "#303446", bg = "#e78284" })
h(0, "@comment.documentation", { link = "Comment" })
h(0, "@comment", { link = "Comment" })
h(0, "@punctuation.special", { link = "Special" })
h(0, "@punctuation.bracket", { fg = "#949cbb" })
h(0, "@punctuation.delimiter", { link = "Delimiter" })
h(0, "@keyword.export", { fg = "#ca9ee6" })
h(0, "@keyword.directive.define", { link = "Define" })
h(0, "@keyword.directive", { link = "PreProc" })
h(0, "@keyword.conditional.ternary", { link = "Operator" })
h(0, "@text.title", { fg = "#8caaee" })
h(0, "@method.php", { link = "Function" })
h(0, "@text.title.6.markdown", { link = "rainbow6" })
h(0, "@text.title.5.markdown", { link = "rainbow5" })
h(0, "@text.literal", { fg = "#a6d189" })
h(0, "@variable", { fg = "#c6d0f5" })
h(0, "@variable.builtin", { fg = "#e78284" })
h(0, "@variable.parameter", { fg = "#ea999c" })
h(0, "@string", { link = "String" })
h(0, "@string.regexp", { fg = "#f4b8e4" })
h(0, "@string.special", { link = "Special" })
h(0, "@string.special.symbol", { fg = "#eebebe" })
h(0, "@punctuation.delimiter.regex", { link = "@string.regexp" })
h(0, "@character.special", { link = "SpecialChar" })
h(0, "@number", { link = "Number" })
h(0, "@define", { link = "Define" })
h(0, "@keyword.storage", { link = "Keyword" })
h(0, "@type.qualifier", { link = "Keyword" })
h(0, "@text.diff.delete", { link = "diffRemoved" })
h(0, "@text.diff.add", { link = "diffAdded" })
h(0, "@method.call", { link = "Function" })
h(0, "@method", { link = "Function" })
h(0, "@text.danger", { fg = "#303446", bg = "#e78284" })
h(0, "@text.note", { fg = "#303446", bg = "#8caaee" })
h(0, "@type", { link = "Type" })
h(0, "@type.definition", { link = "Type" })
h(0, "@property", { fg = "#babbf1" })
h(0, "@function.call", { link = "Function" })
h(0, "@function.method", { link = "Function" })
h(0, "@keyword.type", { link = "Keyword" })
h(0, "@keyword", { link = "Keyword" })
h(0, "@constructor", { fg = "#e5c890" })
h(0, "@text.reference", { fg = "#babbf1" })
h(0, "@text.todo.checked", { fg = "#a6d189" })
h(0, "@text.todo.unchecked", { fg = "#838ba7" })
h(0, "@text.todo", { fg = "#303446", bg = "#eebebe" })
h(0, "@text.warning", { fg = "#303446", bg = "#e5c890" })
h(0, "TelescopeBorder", { link = "FloatBorder" })
h(0, "TelescopeNormal", { link = "NormalFloat" })
h(0, "TelescopePreviewNormal", { link = "TelescopeNormal" })
h(0, "TelescopePromptNormal", { link = "TelescopeNormal" })
h(0, "TelescopeResultsNormal", { link = "TelescopeNormal" })
h(0, "TelescopeTitle", { link = "FloatTitle" })
h(0, "TelescopeSelectionCaret", { fg = "#eebebe", bg = "#414559" })
h(0, "TelescopeSelection", { fg = "#eebebe", bold = true, bg = "#414559" })
h(0, "TelescopeMatching", { fg = "#8caaee" })
h(0, "TelescopePromptPrefix", { fg = "#eebebe" })
h(0, "@preproc", { link = "PreProc" })
h(0, "@storageclass", { link = "Keyword" })
h(0, "@conditional", { link = "Conditional" })
h(0, "@exception", { link = "Exception" })
h(0, "@include", { link = "Include" })
h(0, "@repeat", { link = "Repeat" })
h(0, "@symbol.ruby", { fg = "#eebebe" })
h(0, "@constant.macro", { link = "Macro" })
h(0, "@constant", { link = "Constant" })
h(0, "@text.title.1.markdown", { link = "rainbow1" })
h(0, "@text.title.2.markdown", { link = "rainbow2" })
h(0, "@text.title.3.markdown", { link = "rainbow3" })
h(0, "@text.title.4.markdown", { link = "rainbow4" })
h(0, "TreesitterContext", { fg = "#c6d0f5", bg = "NONE" })
h(0, "TreesitterContextBottom", { underline = true, sp = "#2A2D3E" })
h(0, "TreesitterContextLineNumber", { fg = "#f2d5cf" })
h(0, "@method.call.php", { link = "Function" })
h(0, "@text.environment.name", { fg = "#8caaee" })
h(0, "@text.environment", { fg = "#f4b8e4" })
h(0, "@text.math", { fg = "#8caaee" })
h(0, "@text.strike", { fg = "#c6d0f5", strikethrough = true })
h(0, "@text.underline", { link = "Underlined" })
h(0, "@text.emphasis", { fg = "#e78284", italic = true })
h(0, "@markup.heading.6.markdown", { link = "rainbow6" })
h(0, "@markup.heading.5.markdown", { link = "rainbow5" })
h(0, "@markup.heading.4.markdown", { link = "rainbow4" })
h(0, "@markup.heading.3.markdown", { link = "rainbow3" })
h(0, "@markup.heading.2.markdown", { link = "rainbow2" })
h(0, "@markup.heading.1.markdown", { link = "rainbow1" })
h(0, "@variable.parameter.bash", { fg = "#a6d189" })
h(0, "@function.builtin.bash", { fg = "#e78284", italic = true })
h(0, "@error", { link = "Error" })
h(0, "@tag.delimiter", { fg = "#81c8be" })
h(0, "@tag.attribute", { fg = "#e5c890", italic = true })
h(0, "@tag.builtin", { fg = "#8caaee" })
h(0, "@tag", { fg = "#8caaee" })
h(0, "@diff.delta", { link = "diffChanged" })
h(0, "@diff.minus", { link = "diffRemoved" })
h(0, "@diff.plus", { link = "diffAdded" })
h(0, "@markup.list.unchecked", { fg = "#838ba7" })
h(0, "@markup.list.checked", { fg = "#a6d189" })
h(0, "@markup.list", { fg = "#81c8be" })
h(0, "@markup.raw", { fg = "#a6d189" })
h(0, "@markup.link.url", { fg = "#8caaee", italic = true, underline = true })
h(0, "@markup.link", { fg = "#babbf1" })
h(0, "@markup.environment.name", { fg = "#8caaee" })
h(0, "@markup.environment", { fg = "#f4b8e4" })
h(0, "@markup.quote", { fg = "#f4b8e4" })
h(0, "@markup.math", { fg = "#8caaee" })
h(0, "@markup.heading.markdown", { bold = true })
h(0, "@markup.heading", { fg = "#8caaee" })
h(0, "@markup.underline", { link = "Underlined" })
h(0, "@function.builtin", { fg = "#ef9f76" })
h(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
h(0, "@lsp.type.variable", {  })
h(0, "@lsp.type.enumMember", { fg = "#81c8be" })
h(0, "diffIndexLine", { fg = "#81c8be" })
h(0, "diffLine", { fg = "#737994" })
h(0, "diffFile", { fg = "#8caaee" })
h(0, "diffNewFile", { fg = "#ef9f76" })
h(0, "diffOldFile", { fg = "#e5c890" })
h(0, "diffChanged", { fg = "#8caaee" })
h(0, "diffRemoved", { fg = "#e78284" })
h(0, "CmpItemAbbrMatch", { fg = "#c6d0f5", bold = true })
h(0, "CmpItemAbbrMatchFuzzy", { fg = "#c6d0f5", bold = true })
h(0, "CmpItemKindSnippet", { fg = "#ca9ee6" })
h(0, "CmpItemKindKeyword", { fg = "#e78284" })
h(0, "CmpItemKindText", { fg = "#81c8be" })
h(0, "MiniDiffSignDelete", { fg = "#e78284" })
h(0, "CmpItemKindConstructor", { fg = "#8caaee" })
h(0, "CmpItemKindFolder", { fg = "#8caaee" })
h(0, "CmpItemKindModule", { fg = "#8caaee" })
h(0, "CmpItemKindConstant", { fg = "#ef9f76" })
h(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
h(0, "RenderMarkdownH6", { fg = "#babbf1" })
h(0, "RenderMarkdownH6Bg", { bg = "#575A76" })
h(0, "CmpItemKindColor", { fg = "#e78284" })
h(0, "CmpItemKindReference", { fg = "#e78284" })
h(0, "CmpItemKindEnumMember", { fg = "#e78284" })
h(0, "CmpItemKindStruct", { fg = "#8caaee" })
h(0, "CmpItemKindValue", { fg = "#ef9f76" })
h(0, "CmpItemKindEvent", { fg = "#8caaee" })
h(0, "CmpItemKindOperator", { fg = "#8caaee" })
h(0, "CmpItemKindTypeParameter", { fg = "#8caaee" })
h(0, "CmpItemKindCopilot", { fg = "#81c8be" })
h(0, "MiniFilesTitle", { link = "FloatTitle" })
h(0, "CmpItemKindFile", { fg = "#8caaee" })
h(0, "LspDiagnosticsVirtualTextError", { fg = "#e78284", italic = true })
h(0, "LspDiagnosticsVirtualTextWarning", { fg = "#e5c890", italic = true })
h(0, "LspDiagnosticsVirtualTextInformation", { fg = "#99d1db", italic = true })
h(0, "LspDiagnosticsVirtualTextHint", { fg = "#81c8be", italic = true })
h(0, "LspDiagnosticsUnderlineError", { underline = true, sp = "#e78284" })
h(0, "LspDiagnosticsUnderlineWarning", { underline = true, sp = "#e5c890" })
h(0, "IlluminatedWordText", { bg = "#474D61" })
h(0, "IlluminatedWordRead", { bg = "#474D61" })
h(0, "DapBreakpoint", { fg = "#e78284" })
h(0, "DapBreakpointCondition", { fg = "#e5c890" })
h(0, "DapBreakpointRejected", { fg = "#ca9ee6" })
h(0, "DapLogPoint", { fg = "#99d1db" })
h(0, "DapStopped", { fg = "#ea999c" })
h(0, "RenderMarkdownH1Bg", { bg = "#634A57" })
h(0, "MiniFilesDirectory", { link = "Directory" })
h(0, "CmpItemKindProperty", { fg = "#a6d189" })
h(0, "IlluminatedWordWrite", { bg = "#474D61" })
h(0, "RenderMarkdownH5", { fg = "#85c1dc" })
h(0, "RenderMarkdownH3", { fg = "#e5c890" })
h(0, "RenderMarkdownH3Bg", { bg = "#635D5B" })
h(0, "RenderMarkdownH4", { fg = "#a6d189" })
h(0, "Comment", { fg = "#949cbb", italic = true })
h(0, "SpecialComment", { link = "Special" })
h(0, "DapUIScope", { fg = "#99d1db" })
h(0, "DapUIType", { fg = "#ca9ee6" })
h(0, "DapUIValue", { fg = "#99d1db" })
h(0, "DapUIVariable", { fg = "#c6d0f5" })
h(0, "DapUIModifiedValue", { fg = "#ef9f76" })
h(0, "DapUIDecoration", { fg = "#99d1db" })
h(0, "DapUIThread", { fg = "#a6d189" })
h(0, "DapUIStoppedThread", { fg = "#99d1db" })
h(0, "DapUISource", { fg = "#babbf1" })
h(0, "DapUILineNumber", { fg = "#99d1db" })
h(0, "DapUIFloatBorder", { link = "FloatBorder" })
h(0, "DapUIWatchesEmpty", { fg = "#ea999c" })
h(0, "DapUIWatchesValue", { fg = "#a6d189" })
h(0, "DapUIWatchesError", { fg = "#ea999c" })
h(0, "DapUIBreakpointsPath", { fg = "#99d1db" })
h(0, "DapUIBreakpointsInfo", { fg = "#a6d189" })
h(0, "DapUIBreakpointsCurrentLine", { fg = "#a6d189", bold = true })
h(0, "DapUIBreakpointsDisabledLine", { fg = "#626880" })
h(0, "DapUIStepOver", { fg = "#8caaee" })
h(0, "DapUIStepOverNC", { link = "DapUIStepOver" })
h(0, "DapUIStepInto", { fg = "#8caaee" })
h(0, "DapUIStepIntoNC", { link = "DapUIStepInto" })
h(0, "DapUIStepBack", { fg = "#8caaee" })
h(0, "DapUIStepBackNC", { link = "DapUIStepBack" })
h(0, "DapUIStepOut", { fg = "#8caaee" })
h(0, "DapUIStepOutNC", { link = "DapUIStepOut" })
h(0, "DapUIStop", { fg = "#e78284" })
h(0, "DapUIStopNC", { link = "DapUIStop" })
h(0, "DapUIPlayPause", { fg = "#a6d189" })
h(0, "DapUIPlayPauseNC", { link = "DapUIPlayPause" })
h(0, "DapUIRestart", { fg = "#a6d189" })
h(0, "DapUIRestartNC", { link = "DapUIRestart" })
h(0, "DapUIUnavailable", { fg = "#51576d" })
h(0, "DapUIUnavailableNC", { link = "DapUIUnavailable" })
h(0, "DapUIWinSelect", { fg = "#ef9f76" })
h(0, "qfFileName", { fg = "#8caaee" })
h(0, "htmlH1", { fg = "#f4b8e4", bold = true })
h(0, "htmlH2", { fg = "#8caaee", bold = true })
h(0, "mkdCodeDelimiter", { fg = "#c6d0f5", bg = "#303446" })
h(0, "mkdCodeStart", { fg = "#eebebe", bold = true })
h(0, "mkdCodeEnd", { fg = "#eebebe", bold = true })
h(0, "debugPC", { bg = "NONE" })
h(0, "debugBreakpoint", { fg = "#737994", bg = "#303446" })
h(0, "illuminatedWord", { bg = "#51576d" })
h(0, "illuminatedCurWord", { bg = "#51576d" })
h(0, "DashboardShortCut", { fg = "#f4b8e4" })
h(0, "DashboardHeader", { fg = "#8caaee" })
h(0, "DashboardCenter", { fg = "#a6d189" })
